# Generated by Django 2.2.5 on 2019-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0003_auto_20191117_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
