# Generated by Django 2.2.5 on 2019-11-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0004_auto_20191119_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True)),
                ('friends', models.TextField(blank=True)),
            ],
        ),
    ]
