# Generated by Django 2.2.5 on 2019-11-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0005_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
