# Generated by Django 2.2.5 on 2019-11-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0006_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friends',
            new_name='req_frd',
        ),
    ]
