# Generated by Django 2.2.5 on 2019-11-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0007_auto_20191122_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='frd',
            field=models.TextField(blank=True),
        ),
    ]
