# Generated by Django 2.2.5 on 2019-11-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0008_friend_frd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='req_frd',
            new_name='pending_frd',
        ),
        migrations.AddField(
            model_name='friend',
            name='requested_frd',
            field=models.TextField(blank=True),
        ),
    ]
